module.exports = {
  rules: {
    "@typescript-eslint/explicit-function-return-type": 'off',
    "@typescript-eslint/no-explicit-any": 'off',
    "@typescript-eslint/no-unused-vars": ['error', {"ignoreRestSiblings": true}],
    "@typescript-eslint/no-use-before-define": ['off'],
    "@typescript-eslint/no-var-requires": ['error'],
    "arrow-spacing": ['error'],
    "camelcase": ['error', {"ignoreDestructuring": true}],
    "comma-dangle": ['error', {functions: 'only-multiline', imports: 'only-multiline', objects: 'only-multiline', arrays: 'only-multiline', exports: 'never'}],
    "curly": ['error', 'all'],
    "eqeqeq": ['error', 'always'],
    "no-async-promise-executor": 'error',
    "no-delete-var": ['error'],
    "no-else-return": ['error'],
    "no-extra-bind": ['error'],
    "no-floating-decimal": ['error'],
    "no-multi-spaces": ['error'],
    "no-return-await": 'error',
    "no-self-assign": ['error', {props: true}],
    "no-undef": ['off'], // handled by tsc
    "no-unused-vars": ['error', {"ignoreRestSiblings": true}],
    "no-use-before-define": ['off'],
    "no-useless-rename": ['error'],
    "no-useless-return": ['error'],
    "no-var": ['error'],
    "no-with": ['error'],
    "prefer-arrow-callback": ['error'],
    "prefer-const": ['error'],
    "prefer-numeric-literals": ['error'],
    "prefer-template": ['error'],
    "quotes": ['error', 'single', {allowTemplateLiterals: true}],
    "require-atomic-updates": 'error',
    "require-await": 'error',
    "semi": ['error', 'always'],
    "use-isnan": ['error'],
  }
};
